### ISSUE TITLE
What connectors to use?

### ISSUE THREAD

**Issue by zhou13** [joeljacobs/DSUButtons#2]
Hi Joel Jacobs,

Thanks for your posting your interesting project! One question I have is that what connectors did you use when you wired your DSUButtons? Is it possible to do that without cutting/splicing the origin cables in the car?  I guess I could buy an addition 90980-12422 but I do not know the part number for the female connector.

Thank you!

Best,
Yichao Zhou.

**Comment by arne182** [comment]
3D printed Part 1612050 https://www.thingiverse.com/thing:3170223 Connector F 90980-12422 https://www.toyotapartsdeal.com/oem/toyota~housing~connector~f~90980-12422.html

**Comment by zhou13** [comment]
Awesome. Thanks!
